In [1]:
import numpy as np
from scipy.optimize import minimize, differential_evolution

In [2]:
# создание произвольного нормального вектора размерности 4 -> далее
# из него через функцию generate_complex_vector можно сделать вектор размерности 2 из комплексных чисел
def generateState():
    s0 = np.random.random_sample() * 2 - 1
    s1 = np.random.random_sample() * 2 - 1
    s2 = np.random.random_sample() * 2 - 1
    s3 = np.random.random_sample() * 2 - 1
    state = np.array([s0, s1, s2, s3]/np.sqrt(s0 ** 2 + s1 ** 2 + s2 ** 2 + s3 ** 2))
    return state

In [3]:
generateState()

array([ 0.67236243, -0.53077643, -0.19816442,  0.47637801])

In [4]:
password = 'gaiphi7aan'

process_index = 0
number_of_states = 100

# вещественная основа для входного вектора
state = np.array([1, 0, 0, 0])

# вещественная основа для базиса в котором проводим измерение
projector = np.array([1, 0, 0, 0])

In [5]:
# функция для создания комплексного вектора из вещественной основы
def generate_complex_vector(state):
    return( state[0]+state[1]*1j,  state[2]+state[3]*1j )

In [6]:
# входной вектор (комплексные числа)
alpha, beta = generate_complex_vector(state) 

# комплексный базис измерения
m, n = generate_complex_vector(projector)

In [7]:
# расчет теоритической вероятности 
def probability(a, b, phi, alpha, beta, m, n):
    part1 = np.abs(m) ** 2 * np.abs((a * alpha + b * beta)) ** 2
    part2 = np.conj(m) * n * (a*alpha + b*beta) * np.exp(-phi*1j) * (a*np.conj(beta) - alpha*np.conj(b))
    part3 = m * np.conj(n) * (np.conj(a)*np.conj(alpha) + np.conj(b)*np.conj(beta)) * np.exp(phi*1j) * (np.conj(a)*beta - np.conj(b)*alpha)
    part4 = np.abs(n) ** 2 * np.abs(np.conj(a)*beta - alpha*np.conj(b))
    return part1 + part2 + part3 + part4

In [8]:
# функция расчёта ошибки
def loss_function(a, b , phi):
    for result_item in result:
        # получение величин измерения
        state = result_item[0]
        projector = result_item[1]
        p0_measured = result_item[2]
        
        # вычисление теоритической вероятности
        p0_theoretical = 

SyntaxError: invalid syntax (<ipython-input-8-5905b73222ea>, line 10)

In [11]:
state = generateState()
projector = generateState()

# входной вектор (комплексные числа)
alpha, beta = generate_complex_vector(state) 

# комплексный базис измерения
m, n = generate_complex_vector(projector)

# Initial parameters
a = 1+0*1j
b = 0
phi = 0

probability(a, b, phi, alpha, beta, m, n)

(0.4037502482214075+0j)

In [19]:
# функция измерения состояния

def run_measurement(state, projector, process_index=5, number_of_states=100):
    import socket, sys

    #request = password + ' 1 100 0.5 0.5 0.5 0.5 1 0 0 0'

    request = password + ' ' + str(process_index)+ ' ' + str(number_of_states) + ' ' + \
    ' '.join([str(elem) for elem in np.append(state, projector)])


    host = 'ape.qotlabs.org'
    port = 2018

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(2)

    try:
        s.connect((host, port))
    except:
        print('Unable to connect')
        sys.exit()

    s.send(request.encode())
    data = s.recv(4096).decode()
    n = [int(item) for item in data.split()]
    return(n[0], n[1])

In [17]:
from tqdm import tqdm

ModuleNotFoundError: No module named 'tqdm'

In [20]:
%%time
result5 = []
for i in range(0,100):
    # генерируем вход. состояние
    state = generateState()
    projector = generateState()
    n = run_measurement(state, projector)
    p0 = n[0] / number_of_states
    result4.append((state, projector, p0))
    print(i)
    
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Wall time: 8.59 s


In [15]:
result[0][0], result[0][1], result[0][2]

NameError: name 'result' is not defined

In [25]:
result5 = result4[100:]

In [26]:
result4 = result4[:100]

In [28]:
result3

[(array([ 0.44711885,  0.1736864 ,  0.62860613, -0.61218633]),
  array([0.43200885, 0.68096464, 0.36551463, 0.4648167 ]),
  0.34),
 (array([-0.26851268, -0.86006968, -0.34099716,  0.26814552]),
  array([-0.14490874, -0.62797967,  0.7643664 , -0.01967233]),
  0.89),
 (array([-0.55172317, -0.43415845, -0.484142  ,  0.52222075]),
  array([ 0.1615619 , -0.06253071, -0.92634202,  0.33448188]),
  0.77),
 (array([-0.39926093,  0.12377341,  0.19629993, -0.88698207]),
  array([ 0.07889868,  0.74367177, -0.2858864 , -0.59916297]),
  0.35),
 (array([ 0.43979552, -0.25064012, -0.74229853, -0.43903568]),
  array([-0.70163515,  0.20542284, -0.00634697, -0.6822531 ]),
  0.31),
 (array([ 0.70042081, -0.11700641, -0.66845701, -0.22110045]),
  array([-0.47850139,  0.44028101, -0.41687063,  0.63514402]),
  0.98),
 (array([ 0.3884547 , -0.55398512, -0.51375978,  0.52749818]),
  array([ 0.24686552, -0.65524669, -0.18291085, -0.69011072]),
  0.99),
 (array([0.25005946, 0.41788092, 0.43622226, 0.75667426]),


In [31]:
import os
import pickle

with open('dump3.pkl', 'wb') as file:
    pickle.dump(file, result3, protocol=2)

TypeError: file must have a 'write' attribute